# Generated by Django 3.1.2 on 2020-11-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('email_address', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=20)),
                ('card_number', models.CharField(max_length=30, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
