# Generated by Django 3.1.2 on 2020-11-30 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image_url', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'airlines',
            },
        ),
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.airline')),
            ],
            options={
                'db_table': 'airplanes',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('remaining_seat', models.IntegerField()),
                ('tatal_seat', models.IntegerField()),
                ('airplane_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.airplane')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('initial', models.CharField(max_length=10)),
                ('image_url', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'Regions',
            },
        ),
        migrations.CreateModel(
            name='SeatType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'seatypes',
            },
        ),
        migrations.CreateModel(
            name='Reservation_age',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('age_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.age')),
                ('reservation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.reservation')),
            ],
            options={
                'db_table': 'reservation_ages',
            },
        ),
        migrations.CreateModel(
            name='Product_reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.IntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('reservation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.reservation')),
            ],
            options={
                'db_table': 'product_reservations',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='seat_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.seattype'),
        ),
        migrations.AddField(
            model_name='airplane',
            name='from_region_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_region_id', to='products.region'),
        ),
        migrations.AddField(
            model_name='airplane',
            name='to_region_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_region_id', to='products.region'),
        ),
    ]
