# Generated by Django 3.1.2 on 2020-12-02 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image_url', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'airlines',
            },
        ),
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('airplane_numbers', models.CharField(max_length=15)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.airline')),
            ],
            options={
                'db_table': 'airplanes',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('region_code', models.CharField(max_length=10)),
                ('image_url', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'regions',
            },
        ),
        migrations.CreateModel(
            name='SeatType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'seat_types',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('remaining_seat', models.IntegerField()),
                ('total_seats', models.IntegerField()),
                ('airplane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.airplane')),
                ('seat_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.seattype')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.AddField(
            model_name='airplane',
            name='from_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_region', to='products.region'),
        ),
        migrations.AddField(
            model_name='airplane',
            name='to_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_region', to='products.region'),
        ),
    ]
